#Begin: configuration of porting application
application_name := h2o
native_application_location = enclave/$(application_name)/build
make_target :=
native_application_executable := $(native_application_location)/$(application_name)
#End: configuration of porting application

include common.mk
